apply plugin: 'com.android.application'

android {
    namespace "com.ghostlock.skeleton"
    compileSdk 34

    defaultConfig {
        applicationId "com.ghostlock.skeleton"
        minSdk 29
        targetSdk 34
        versionCode 1
        versionName "1.0-skeleton"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
}
